const TYPES = {
	CLEAR_NOTICE: 'CLEAR_NOTICE',
	MOVE_PEG: 'MOVE_CHECKER',
	NEXT_PLAYER: 'NEXT_PLAYER',
	RESET_STATE: 'RESET_STATE',
	ROLL_DIE: 'ROLL_DIE',
	SET_NOTICE: 'SET_NOTICE',
};

export default TYPES;
